import { describe, it, expect } from "vitest";

// The bindings are generated by `npm run build` into dist/.
// These tests verify the generated client compiles and exposes
// the expected Soroban contract API surface.
import {
  Client,
  networks,
} from "../dist/index.js";

describe("AlertRegistry bindings", () => {
  const testnetConfig = {
    contractId: networks.testnet.contractId,
    networkPassphrase: networks.testnet.networkPassphrase,
    rpcUrl: networks.testnet.rpcUrl,
  };

  it("exports a Client class", () => {
    expect(Client).toBeDefined();
    expect(typeof Client).toBe("function");
  });

  it("exports network configurations for testnet", () => {
    expect(networks).toBeDefined();
    expect(networks.testnet).toBeDefined();
    expect(networks.testnet.contractId).toMatch(/^C[A-Z0-9]{55}$/);
    expect(networks.testnet.networkPassphrase).toBe(
      "Test SDF Network ; September 2015"
    );
    expect(networks.testnet.rpcUrl).toBe("https://soroban-testnet.stellar.org");
  });

  it("can instantiate Client with testnet config", () => {
    const client = new Client(testnetConfig);
    expect(client).toBeDefined();
  });

  it("exposes expected read methods on the Client prototype", () => {
    const client = new Client(testnetConfig);
    // Read-only methods (no auth required)
    expect(typeof client.get_alert).toBe("function");
    expect(typeof client.get_alerts_for_contract).toBe("function");
    expect(typeof client.get_alerts_by_owner).toBe("function");
    expect(typeof client.get_alert_count).toBe("function");
    expect(typeof client.get_active_alert_count).toBe("function");
    expect(typeof client.get_admin).toBe("function");
    expect(typeof client.get_per_owner_alert_limit).toBe("function");
  });

  it("exposes expected write methods on the Client prototype", () => {
    const client = new Client(testnetConfig);
    // Write methods (auth required)
    expect(typeof client.register_alert).toBe("function");
    expect(typeof client.update_alert).toBe("function");
    expect(typeof client.update_webhook).toBe("function");
    expect(typeof client.remove_alert).toBe("function");
    expect(typeof client.initialize).toBe("function");
  });
});
