#!/usr/bin/env bash
# scripts/check-docs.sh — Check rustdoc coverage and intra-doc links for both contracts
#
# 1. `missing_docs`: every public item written in the contracts must carry a
#    doc comment (items generated by Soroban's macros are exempt; see
#    check_missing_docs.py).
# 2. `rustdoc::broken_intra_doc_links`: every [`link`] in a doc comment must
#    resolve. Note that `#[contractimpl]` copies each method's docs into a
#    generated module, so links there must use `AlertRegistry::…` /
#    `WatcherRegistry::…` rather than `Self::…`.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGES=(-p alert-registry -p watcher-registry)

echo "==> missing_docs"
RUSTFLAGS="${RUSTFLAGS:-} -W missing_docs" \
  cargo check --locked --lib "${PACKAGES[@]}" --message-format=json \
  | python3 "${SCRIPT_DIR}/check_missing_docs.py"

echo "==> rustdoc::broken_intra_doc_links"
RUSTDOCFLAGS="${RUSTDOCFLAGS:-} -D rustdoc::broken_intra_doc_links" \
  cargo doc --no-deps --locked "${PACKAGES[@]}"
